// <auto-generated />
using System;
using ASM_C_6_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_C_6_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_C_6_API.Model.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ComboId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            AddedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CartId = 1,
                            FoodItemId = 1,
                            Quantity = 1,
                            UnitPrice = 6.99m
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Rice Dishes",
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cơm và các món ăn kèm truyền thống",
                            ImageUrl = "/images/categories/rice.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Noodles",
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phở, mì và các món bún",
                            ImageUrl = "/images/categories/noodles.jpg",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drinks",
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nước giải khát: trà, nước ngọt, nước trái cây",
                            ImageUrl = "/images/categories/drinks.jpg",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ComboName = "Lunch Combo",
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gồm 1 cơm gà + 1 trà đá",
                            DiscountPrice = 7.99m,
                            ImageUrl = "/images/combos/lunch_combo.jpg",
                            IsAvailable = true,
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.ComboItem", b =>
                {
                    b.Property<int>("ComboItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboItemId"));

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ComboItemId");

                    b.HasIndex("ComboId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("ComboItems");

                    b.HasData(
                        new
                        {
                            ComboItemId = 1,
                            ComboId = 1,
                            FoodItemId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ComboItemId = 2,
                            ComboId = 1,
                            FoodItemId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gà nướng sốt đặc biệt phục vụ cùng cơm trắng",
                            FoodName = "Grilled Chicken with Rice",
                            ImageUrl = "/images/food/grilled_chicken.jpg",
                            IsAvailable = true,
                            Price = 6.99m,
                            Theme = "Savory"
                        },
                        new
                        {
                            FoodItemId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phở bò thơm ngon với nước dùng đậm đà",
                            FoodName = "Beef Pho",
                            ImageUrl = "/images/food/beef_pho.jpg",
                            IsAvailable = true,
                            Price = 5.50m,
                            Theme = "Traditional"
                        },
                        new
                        {
                            FoodItemId = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trà đá mát lạnh",
                            FoodName = "Iced Tea",
                            ImageUrl = "/images/food/iced_tea.jpg",
                            IsAvailable = true,
                            Price = 1.50m,
                            Theme = "Refreshing"
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            DeliveryAddress = "123 Example Street",
                            IsPaid = false,
                            Note = "Giao giờ hành chính",
                            OrderDate = new DateTime(2025, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 0,
                            PhoneNumber = "0987654321",
                            ReceiverName = "John Doe",
                            Status = 0,
                            TotalAmount = 6.99m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity] * [UnitPrice]");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ComboId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            FoodItemId = 1,
                            OrderId = 1,
                            Quantity = 1,
                            TotalPrice = 6.99m,
                            UnitPrice = 6.99m
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "User"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Nguyendinhnam24109@gmail.com",
                            FirstName = "System",
                            LastName = "Administrator",
                            PasswordHash = "AQAAAAEAACcQNAAAAEJv1y7sX5G6k8jvY9Vh3F4Z2x5Y6Z7X8Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6",
                            PhoneNumber = "0123456789",
                            RefreshToken = "",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "nguyendinhnam288@gmail.com",
                            FirstName = "Regular",
                            LastName = "User",
                            PasswordHash = "AQAAAAEAACcQNAAAAEJv1y7sX5G6k8jvY9Vh3F4Z2x5Y6Z7X8Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6",
                            PhoneNumber = "0987654321",
                            RefreshToken = "",
                            RoleId = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Cart", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ASM_C_6_API.Model.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.CartItem", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM_C_6_API.Model.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ASM_C_6_API.Model.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Combo");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.ComboItem", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.Combo", "Combo")
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM_C_6_API.Model.FoodItem", "FoodItem")
                        .WithMany("ComboItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.FoodItem", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.Category", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Order", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.OrderDetail", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.Combo", "Combo")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ComboId");

                    b.HasOne("ASM_C_6_API.Model.FoodItem", "FoodItem")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FoodItemId");

                    b.HasOne("ASM_C_6_API.Model.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FoodItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.User", b =>
                {
                    b.HasOne("ASM_C_6_API.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Category", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Combo", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.FoodItem", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ASM_C_6_API.Model.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
